// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmRnN5KYMfQIjShVR6kyKxbkqPkUlh4Ro',
    appId: '1:191090790967:web:328a34337f8a97150d25b2',
    messagingSenderId: '191090790967',
    projectId: 'ministry-demos',
    authDomain: 'ministry-demos.firebaseapp.com',
    storageBucket: 'ministry-demos.appspot.com',
    measurementId: 'G-BPBJP8GRV0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNWd2ssRMH5buHNiyoygfj2-nMFGzozyY',
    appId: '1:191090790967:android:a8c1541842d793e10d25b2',
    messagingSenderId: '191090790967',
    projectId: 'ministry-demos',
    storageBucket: 'ministry-demos.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr9aZ-7VfRE6LIhvvSHtdKCblCqvq_Yic',
    appId: '1:191090790967:ios:cf7489211cb2bdc80d25b2',
    messagingSenderId: '191090790967',
    projectId: 'ministry-demos',
    storageBucket: 'ministry-demos.appspot.com',
    iosBundleId: 'com.example.starterArchitectureFlutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBr9aZ-7VfRE6LIhvvSHtdKCblCqvq_Yic',
    appId: '1:191090790967:ios:7911b0d890bc4d1c0d25b2',
    messagingSenderId: '191090790967',
    projectId: 'ministry-demos',
    storageBucket: 'ministry-demos.appspot.com',
    iosBundleId: 'com.example.starterArchitectureFlutterFirebase.RunnerTests',
  );
}
